### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by QUEST2179** [rmarkello/snfpy#18]
Dear developer, 

I tried a real dataset GBM from original paper but got the following error. Could you please help? Thanks!

mirna = pd.read_csv('GLIO_Mirna_Expression.txt', index_col=0, sep='\t')
exp = pd.read_csv('GLIO_Gene_Expression.txt', index_col=0, sep='\t')
methy = pd.read_csv('GLIO_Methy_Expression.txt', index_col=0, sep='\t')
affinity_networks = snf.make_affinity([mirna.T, exp.T, methy.T], metric='euclidean', K=20, mu=0.5)
fused_network = snf.snf(affinity_networks, K=20)

Traceback (most recent call last):
  File "testSNF.py", line 27, in <module>
    fused_network = snf.snf(affinity_networks, K=20)
  File "C:\Users\Miniconda3\lib\site-packages\snf\compute.py", line 392, in snf
    aff = _check_SNF_inputs(aff)
  File "C:\Users\Miniconda3\lib\site-packages\snf\compute.py", line 446, in _check_SNF_inputs
    ac = check_array(a, force_all_finite=True, copy=True)
  File "C:\Users\Miniconda3\lib\site-packages\sklearn\utils\validation.py", line 73, in inner_f
    return f(**kwargs)
  File "C:\Users\Miniconda3\lib\site-packages\sklearn\utils\validation.py", line 646, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "C:\Users\Miniconda3\lib\site-packages\sklearn\utils\validation.py", line 100, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by lillepeder** [comment]
The fault is in the dataset. One patient (ID=TCGA-12-0780-01A...) has only missing values for every modality. I dropped this patient from the dataframes and it runs just fine.
